/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/N9MG8sO4kWW
 */

'use client';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';

import Image from 'next/image';
import { JSX, SVGProps } from 'react';
import { useParams } from 'next/navigation';
import { getCarById } from '@/lib/db';

export async function CarDetails() {
  const { id } = useParams<{ id: string }>();

  const carData = getCarById(id);

  if (!carData) {
    return <div className='text-2xl font-bold text-center'>Car not found</div>;
  }

  const { name, price, overview, features, imageUrl } = carData;

  return (
    <div className='bg-gray-50/90 border-t border-gray-200 dark:border-gray-800'>
      <div className='py-12'>
        <div className='container grid gap-6 px-4 md:gap-12 lg:px-6 xl:grid-cols-2'>
          <Image alt={name} className='aspect-video overflow-hidden rounded-xl object-cover object-center' height={310} src={imageUrl} width={550} />
          <div className='flex flex-col justify-between space-x-4'>
            <div className='grid gap-2'>
              <h1 className='text-3xl font-bold tracking-tighter sm:text-5xl'>{name}</h1>
              <p className='text-2xl font-bold tracking-tighter text-gray-500 md:text-3xl lg:text-4xl/relaxed xl:text-5xl/relaxed dark:text-gray-400'>R {price}/day</p>
            </div>
            <div className='flex items-center justify-end space-x-4'>
              <Button size='lg' variant='outline'>
                <HeartIcon className='mr-2 h-4 w-4' />
                Add to Favorites
              </Button>
            </div>
          </div>
        </div>
      </div>
      <section className='border-t border-b py-12'>
        <div className='container grid items-start gap-6 px-4 md:gap-12 lg:grid-cols-2 lg:px-6'>
          <div className='space-y-4'>
            <div className='space-y-2'>
              <h2 className='text-2xl font-bold tracking-tighter sm:text-3xl'>Overview</h2>
              <p className='text-gray-500 dark:text-gray-400'>{overview}</p>
            </div>
            <div className='space-y-2'>
              <h2 className='text-2xl font-bold tracking-tighter sm:text-3xl'>Features</h2>
              <ul className='grid gap-2'>
                {features.map((feature, index) => (
                  <li key={index}>
                    <CheckIcon className='mr-2 inline-block h-4 w-4' />
                    {feature}
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      </section>
      <section className='py-12'>
        <div className='container px-4 md:px-6'>
          <form className='space-y-6'>
            <div className='grid gap-2'>
              <Label className='text-base' htmlFor='pickup'>
                Pickup Date
              </Label>
              <Input id='pickup' placeholder='Enter pickup date' required type='date' />
            </div>
            <div className='grid gap-2'>
              <Label className='text-base' htmlFor='dropoff'>
                Drop-off Date
              </Label>
              <Input id='dropoff' placeholder='Enter drop-off date' required type='date' />
            </div>
            <div className='grid gap-2'>
              <Label className='text-base' htmlFor='name'>
                Full Name
              </Label>
              <Input id='name' placeholder='Enter your full name' required type='text' />
            </div>
            <div className='grid gap-2'>
              <Label className='text-base' htmlFor='email'>
                Email
              </Label>
              <Input id='email' placeholder='Enter your email' required type='email' />
            </div>
            <div className='grid gap-2'>
              <Label className='text-base' htmlFor='phone'>
                Phone Number
              </Label>
              <Input id='phone' placeholder='Enter your phone number' required type='tel' />
            </div>
            <div className='flex justify-end'>
              <Button className='px-12' type='submit'>
                Rent Now
              </Button>
            </div>
          </form>
        </div>
      </section>
    </div>
  );
}

function HeartIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <path d='M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z' />
    </svg>
  );
}

function CheckIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      strokeWidth='2'
      strokeLinecap='round'
      strokeLinejoin='round'
    >
      <polyline points='20 6 9 17 4 12' />
    </svg>
  );
}
